### PR TITLE
Fix #39

### LINKED ISSUE #39: Its broken on latest paper 1.20.6
/plugman unload fails with "An unexpected error occured trying to execute that command", doesnt print an exception to console, I think a recent paper update has broken it as it worked a week ago.

### PR DESCRIPTION
**Pull request by KojiTadokoro114**
It is a simple issue.
just fix it by "remove after traverse commands".

### CODE REVIEW

**Comment by Test-Account666** [comment]
This made absolutely no difference for me

**Comment by KojiTadokoro114** [comment]
> This made absolutely no difference for me

Have you ever try your and my version in Paper-1.20.6?

On your version (2.3.8)，when unload a plugin with bukkit style registered command: https://pastebin.com/2MZKLbM8

My version fix that.

**Comment by Test-Account666** [comment]
> > This made absolutely no difference for me
> 
> Have you ever try your and my version in Paper-1.20.6?
> 
> On your version (2.3.8)，when unload a plugin with bukkit style registered command: https://pastebin.com/2MZKLbM8
> 
> My version fix that.

I did test it on the latest paper 1.20.6.

Both versions throw an error, but work just fine in the end for me

**Comment by KojiTadokoro114** [comment]
> > > This made absolutely no difference for me
> > 
> > 
> > Have you ever try your and my version in Paper-1.20.6?
> > On your version (2.3.8)，when unload a plugin with bukkit style registered command: https://pastebin.com/2MZKLbM8
> > My version fix that.
> 
> I did test it on the latest paper 1.20.6.
> 
> Both versions throw an error, but work just fine in the end for me

Can you give me the error StackTrace?

In fact, there two type of error, one is UnsupportedOperation, which will create a fatal error on unload plugin so that it can't unloaded. Another is ConcurrentModification, but it won't effect the unload operation.

Thank you!

**Comment by Test-Account666** [comment]
Yes, the ConcurrentModification Exception is what I'm getting.

I know that there seems to be an issue with PlugManX, but I cannot reproduce it.

I could just merge and upload, but I'm unsure if I should, if I cannot reproduce the issue

**Comment by KojiTadokoro114** [comment]
> Yes, the ConcurrentModification Exception is what I'm getting.
> 
> I know that there seems to be an issue with PlugManX, but I cannot reproduce it.
> 
> I could just merge and upload, but I'm unsure if I should, if I cannot reproduce the issue

As the stacktrace I posted,  this issue (ConcurrentModification) is caused by multi-thread operation by paper.
To reproduce it, you can input a command provided by a plugin (don't send it) and reload the plugin from console.
This new version completely fixed it.
image

**Comment by KojiTadokoro114** [comment]
> Have you also tested executing the command after (un-)loading?
> 
> That's also another issue as Paper has changed the command system

After loading is ok, as well as its behavior in 1.20.4
But reloading have some issue, there some issues on vanilla command check (I'm still working on it).

**Comment by KojiTadokoro114** [comment]
Interestingly, ConcurrentModification is caused by code in unload method (bukkitutil -> update).
In order to avoid from destroy the plugin in legacy version of Paper, I use a nother class to process plugin unload of paper 1.20.5+

**Comment by Test-Account666** [comment]
I'll do some testing.

I appreciate the help! :)

**Comment by Test-Account666** [comment]
Direct merge was not possible as I was working on some formatting changes.

Thanks for your help :)

**Pull request closed without merging**
